### ISSUE TITLE
Site section with real examples

### ISSUE THREAD

**Issue by zedejose** [casparhubinger/wpisnotwp.com#5]
Maybe not relevant, but I'm tired of seeing the unchecked propaganda being published, with no corrections or apologies. And yes, at this point, I have no other word for it than "propaganda", since it appears that those are intended, rather than honest mistakes.

What made me write this issue was this:

https://www.poynter.org/news/one-time-npr-and-nyt-digital-chief-new-adventure-wordpress

Specifically:

> ...Automattic Inc., which now powers 29 percent of all sites on the web,...

**Automattic** now powers 29% of the web? Not WordPress.**ORG**?

**Comment by zedejose** [comment]
Oh, and

> ...WordPress.com became the world’s biggest self-hosted blogging tool...

Wat

**Comment by glueckpress** [comment]
Apologies for the late reply, @zedejose, I was on vacation and partially logged off. 🙂 

The thing I like most about [wpisnotwp.com](https://wpisnotwp.com/) is that [it’s pretty hard to disagree with](https://twitter.com/photomatt/status/898277397535051777), let alone to blame it. 

Its central message is an appeal to the reader (“[However, now you know](https://github.com/glueckpress/wpisnotwp.com/blob/master/index.html#L86)”), not criticism—even though you and I, and many others would agree there’s plenty of reason for criticism, or critique. 
I believe if the site does any good, it’s because the only sides it takes is for contributors (real people), not for—or against—organisations (abstract bodies).

Apart from technical implications (format, maintenance etc.), I fear the site’s key appeal to empathy would lose significance if we added a list of problematic examples.

The article you mentioned has been rectified since. Thanks to waybackmachine.org, here’s the diff:

<a href="https://www.diffchecker.com/v3xqd8Wm"><img width="1492" alt="screen shot 2018-02-19 at 09 34 50" src="https://user-images.githubusercontent.com/308422/36368585-3f635628-1558-11e8-838a-66065cc82d6d.png"></a>
(https://www.diffchecker.com/v3xqd8Wm)

Personally, I still want to believe that type of mistake happens on the publisher’s side, not on Automattic’s, although I agree it seems to happen quite often lately. It makes me angry and sad when I notice it, however, it wouldn’t make me happier, or more content to add another URL to a list.

Thanks for raising this issue, it’s well worth discussing.
